lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/Application.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Plugins.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Screen.js
Allow registration of application specific GUI plugins.
=> GUI plugin registry

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/TabView.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/renderer/NoteForm.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
=> Added some missing commas

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
This allows setting a date field value in the config. Format is '2015-09-11', not sure this is what you want.
=> Fix date setter

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/uploadwidget/source/class/uploadwidget/UploadToolbarButton.js
Upload button with toolbar appearence (smaller height).
=> Upload toolbar

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/uploadwidget/source/class/uploadwidget/UploadToolbarButton.js
If a checkbox is initialized from the config with "false" _setData() is actually called with NULL as value.
In any case, I think NULL should be treated as false and not as true.
=> Fix checkbox

lib/CallBackery/qooxdoo/callbackery/config.json, lib/CallBackery/qooxdoo/callbackery/source/translation/de.po, lib/CallBackery/qooxdoo/callbackery/source/translation/en.po
Please check if config.json makes sense like that (it is working at least). Would be nice if you could integration the translation into the Makefile
=> Enable Qooxdoo translations

lib/CallBackery/GuiPlugin/AbstractForm.pm
This change allows to use a Popup from a Popup.
=> PopUp-Rekursion

lib/CallBackery/Database.pm, lib/CallBackery/User.pm
Hi @oetiker 
Please review the PR. It address the pod error reported by CPANTS below:
http://cpants.cpanauthors.org/dist/CallBackery
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Fix pod error as reported by CPANTS.

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Table.js
=> row must be unselected when data is not existing

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/DateTime.js
Hi Tobi,
I actually would only like to have the changes in
lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
merged and
lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/DateTime.js
added.
The rest is "garbage" as I don't seem to be able to properly pull your changes into my repo.
Cheers,
Fritz
=> Date time widget

Makefile.PL, lib/CallBackery.pm, lib/CallBackery/Controller/RpcService.pm, lib/CallBackery/User.pm, t/basic.t
=> activate logging when CALLBACKERY_RPC_LOG is set

lib/CallBackery.pm, lib/CallBackery/GuiPlugin/AbstractForm.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
=> reload readonly fields when a trigger field is executed.

CHANGES, lib/CallBackery.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Popup.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/renderer/NoteForm.js
- pop config option cancelLabel to override label on calcle button in popups
- form field option 'copyOnTap' added to copy readOnly field content to
clipboard on tap.
=> learn about clipboard

.gitignore, CHANGES, Makefile.aperl, lib/CallBackery.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/renderer/NoteForm.js, lib/CallBackery/qooxdoo/callbackery/source/translation/de.po, lib/CallBackery/qooxdoo/callbackery/source/translation/en.po, lib/CallBackery/qooxdoo/callbackery/source/translation/fr.po, lib/CallBackery/qooxdoo/callbackery/source/translation/it.po, lib/CallBackery/qooxdoo/callbackery/update-translation
configurable copyFailMsg and copySuccessMsg per field where copyOnTap is enabled
=> improve copy popup

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
Allow an optional leading minus sign.
=> Allow negative epoch seconds as value of date field

Makefile.PL, lib/CallBackery/GuiPlugin/AbstractTable.pm
Add a method to AbstractTable which allows to add an export
action button in one line, like so:
`$self->makeExportAction()`
=> makeExportAction - XLSX / CSV exporter

CHANGES, lib/CallBackery.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/renderer/NoteForm.js
- fix translation for custom copy messages
=> - fix default wording for succesful copy

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Card.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/CardList.js
- Handle SelectBox as part of Cards
- Make updates work generically for every text field
- Add some checks for undefined data
=> Add missing functionality and checks

lib/CallBackery/GuiPlugin/Abstract.pm, lib/CallBackery/GuiPlugin/AbstractCardlist.pm, lib/CallBackery/GuiPlugin/AbstractForm.pm, lib/CallBackery/Translate.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Card.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/CardList.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
- New backend call `allCardData`
- Default updateCard action
- Make filtering work
- Some cleanup
=> Extend card list

lib/CallBackery/GuiPlugin/AbstractCardlist.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/MsgBox.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Popup.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
- Improve MsgBox
- Fix getData
- Extend showMessage
=> Extend card list again

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Table.js
... to make new form reload work
=> Pass context to action handler

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Screen.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
- remove unnecessary warning for upload
- add userData property to action config and pass it back from the frontend on getPluginConfig
- fix a context (`that = this`) problem probably introduced in a previous PR
=> Action handling

lib/CallBackery/GuiPlugin/AbstractForm.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/HtmlBox.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
- Add HtmlBox with JavaScript enabled.
- Add `save` action
- Use "silent" `callAsync` for actions other than `submit`
=> Add HtmlBox widget and action

lib/CallBackery/GuiPlugin/AbstractAction.pm, lib/CallBackery/GuiPlugin/AbstractForm.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Plugins.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/ActionForm.js
Needed for CrdMgr CM-138:
- New base class `AbstractAction`
- Derive `AbstractForm` from it
- Add action-only frontend class `ActionForm`
=> Action form

lib/CallBackery/GuiPlugin/Users.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Card.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Desktop.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Popup.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Screen.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/TabView.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/DateTime.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/ActionForm.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/CardList.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Table.js
- Add qxObjectIds using backend keys
- Add limited hierarchical structure to ensure id uniqueness (in the backend keys can be identical in the `formCfg` and `actionCfg` hashes) 
- Form elements and actions without `key` attribute are ignored
=> Instrument with qxObjectIds

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
=> Fix exception handler

lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
Camas fixed, not needed anymore.
=> Remove setSelection hack

CHANGES, lib/CallBackery/GuiPlugin/AbstractAction.pm, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
- Allow multiple actions in menu with identical Popup plugin
=> CM-201: generic Popups for menuActions

CHANGES, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Card.js, lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
- Translate placeholder values and tooltip text
- Make foreach function calls consistent
=> Add translations in Card.js
